language: python
python:
  - "3.5.1"
install:
  - pip install -r requirements.txt
  

before_install:
  - python setup.py install
  - pip install codecov

script:
  - py.test
  - coverage run tests/test_async.py
  - coverage run tests/test_sync.py

after_success:
  - codecov



sudo: required
