language: python
python:
  - "3.5.1"
install:
  - pip install -r requirements.txt
  

before_install:
  - python setup.py install
  - pip install codecov pytest-cov pytest-xdist

script:
  - py.test --cov -v

after_success:
  - codecov



sudo: required
