language: python
python:
  - "3.5.1"
install:
  - pip install -r requirements.txt
  

before_install:
  - python setup.py install
  - pip install coveralls pytest-cov pytest-xdist

script:
  - py.test --cov=pyappbase -v

after_success:
  - codecov



sudo: required
